name: PSScriptAnalyzer

on:
  push:
    paths:
      - '**.ps1'
  pull_request:
    paths:
      - '**.ps1'

jobs:
  analyze:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser
          Invoke-ScriptAnalyzer -Path . -Recurse -Severity Warning,Error